language: node_js
node_js:
  - "stable"
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
